language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

sudo: false

matrix:
    fast_finish: true

install:
    # Virtualenv < 14 is required to keep the Python 3.2 builds running.
    #- pip install tox "virtualenv<14"
    - pip install tox-travis

script:
    #- tox -e $TOX_ENV
    - tox
after_success:
    # pip install codecov
    # codecov -e TOX_ENV

notifications:
    email: false
